Blog/users/urls.py
from django.urls import path
from django.conf.urls import url
from .views import  login_view, logout_view, UsersListView, UsersDetailView, activate, signup, UsersProfileDetailView


app_name = 'users'

urlpatterns = [
    #path('signup/', signup_view, name="signup"),
    path('signup/', signup, name="signup"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('<int:pk>/', UsersDetailView.as_view(), name='user'),
    path('profile/<int:pk>/', UsersProfileDetailView.as_view(), name='profile'),
    #pathurl(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #    activate, name='activate'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('', UsersListView.as_view(), name='user_list'),
]

Blog/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('Email addres'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    bio = models.TextField()

    def __str__(self):
        return f'{self.user.email}-{self.bio}'

@receiver(post_save, sender=CustomUser)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

Blog/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class CustomUserAuthenticationForm(AuthenticationForm):

    class Meta:
        model = CustomUser
        fields = ( 'email',)

class SignUpForm(CustomUserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2', )

class LoginForm(forms.Form):

    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user doesn't exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("User no longer Active")
        return super(LoginForm,self).clean(*args,**kwargs)    

Blog/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login,logout, authenticate
from django.urls import reverse
from django.views.generic import ListView, DetailView
import sys


from .forms import SignUpForm, LoginForm
from .models import CustomUser, Profile


from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from django.http import HttpResponse



def signup(request):
    """Signup logic with email verification needs to set user active."""
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            print(sys.stderr, 'in sign up view.....')
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            """Email veryfication for user signup to be active and ability to be login."""
            """Active in activate function down here."""
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def activate(request, uidb64, token):
    """Active with unique link that emailed to user."""
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='users.backends.CustomUserBackend')
        return redirect('pages:home')
        #return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

def login_view(request):
    """Login view , just active users can login."""
    form = LoginForm(data = request.POST)
    if form.is_valid():
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user is not None: # if user exist
            #print(sys.stderr, user.email)
            login(request, user, backend='users.backends.CustomUserBackend')

            """if user redirect to login view from anothe view goes back to his/her way after login"""
            path_redirect = request.get_full_path().split('?next=',1)                   #good piece of code
            if '?next=' in request.get_full_path():# Redirecting After Login 
                return redirect(path_redirect[1])
            else:
                return redirect('pages:home')
                
                 
        return render(request, 'users/login.html', {'form': form, 'error_message': 'Email or Password is wrong!'})
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})



def logout_view(request):
    """logout view, redirect to login view"""
    logout(request)
    return redirect(reverse('users:login'))


class UsersListView(ListView):
    """Show list of all users."""

    queryset =CustomUser.objects.all()
    context_object_name = 'CustomUsers'
    paginate_by = 10
    template_name = 'users/list.html'


class UsersDetailView(DetailView): #todo  change to profile.
    """Show user detail, but can be user profile."""

    model = CustomUser

    context_object_name = 'CustomUser'
    queryset = CustomUser.objects.all()
    template_name = 'users/detail.html'



class UsersProfileDetailView(DetailView):
    """Show user profile."""
    
    model = Profile

    context_object_name = 'Profile'
    queryset = Profile.objects.all()
    template_name = 'users/profile.html'

Blog/users/templates/users/acc_active_email.html
{% autoescape off %}
    Hi {{ user.email }},
    Please click on the link to confirm your registration,

    http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

Blog/users/templates/users/detail.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}Our Blog{% endblock %}

{% block content %}
    <h1>user page</h1>
    <h2> {{ CustomUser.profile.first_name }} {{ CustomUser.profile.last_name }}</h2>
    <p> {{ CustomUser.email }} - date joined us : {{ CustomUser.date_joined }}</p>
    <p> {{ CustomUser.profile.bio }}</p>
    <p>user profile<a href="{% url "users:profile" CustomUser.id %}">profile</a></p>
    <a href="{% url "posts:user_post_list" CustomUser.id %}">posts</a>-
    <a href="{% url "posts:user_commented_post_list" CustomUser.id %}">comments</a>
{% endblock %}

Blog/users/templates/users/list.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}

<div class="container m-1">
  <div class="col-10">
        {% for CustomUser in CustomUsers %}
        <div class="border p-1 m-3">
          
          <p>
            {% if CustomUser.profile.first_name %}
              {{ CustomUser.profile.first_name }}-{{ CustomUser.profile.last_name }}
              <br><a href="{% url "users:user" CustomUser.id %}">{{ CustomUser.email }}</a>
            {% else %}
            <a href="{% url "users:user" CustomUser.id %}">
            {{ CustomUser.email }}</a>
            {% endif %}
            <br>joined: {{ CustomUser.date_joined }}
          </p>
        </div>
      {% endfor %}
      {% include "pagination.html" with page=page_obj %}
  </div>
</div>

{% endblock %}

Blog/users/templates/users/login.html
{% extends "posts/base.html" %}

{% block title %}Log in{% endblock %}


{% block content %}

<div class="container m-1">
  <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}
      <div class="col-10">
          <div class="panel panel-default">
              <div class="panel-heading m-3">Login</div>
              <div class="panel-body">
                  {% if error_message %}
                      <p class="bg-gradient ">{{ error_message }}</p>
                  {% endif %}
                  <div class="form-group clearfix">
                      <label for="email" class="col-6 control-label text-right">Email:</label>
                      <div class="col-6">
                          <input name="email" value="" type="text" class="form-control" />
                      </div>
                  </div>
                  <div class="form-group clearfix">
                      <label for="password" class="col-6 control-label text-right">Password:</label>
                      <div class="col-6">
                          <input name="password" type="password" class="form-control" />
                      </div>
                  </div>
                  <div class="col-md-6 col-md-offset-4 m-1">
                      <input name="login" type="submit" value="Login" class="btn btn-success" /> &nbsp;
                      <a href="{% url 'users:signup' %}">or Signup</a>
                  </div>
                  <input type="hidden" name="next" value="{{ request.GET.next }}"/>
              </div>
          </div>
      </div>
      
  </form>
</div>



{% endblock %}  

















<!-- 
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Login</button>
</form> -->

Blog/users/templates/users/profile.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}{{ Profile.user.email }} Profile{% endblock %}

{% block content %}
    <h1>Profile</h1>
    <h2> {{ Profile.first_name }} {{ Profile.last_name }}</h2>
    <p> {{ Profile.user.email }} - date joined us : {{ Profile.user.date_joined }}</p>
    <p> {{ Profile.bio }}</p>
{% endblock %}


{% block content2 %}
<div class="container">
    <div class="row py-3">
        <div class="col-6">
            <p>{{ Profile.user.blog_posts.all | length }} <a href="{% url "posts:user_post_list" Profile.user.id %}">posts</a></p>
            {% for post in Profile.user.blog_posts.all %}
                <div class="border border-info p-1 m-1">
                    <div class="border p-1 m-3 col-11">
                    <h4>
                        <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                        </a>
                    </h4>
                        Tags:
                        {% for tag in post.tags.all %}
                        <a href="{% url "posts:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <p class="date">
                        Published {{ post.publish }} by {{ post.author }}
                    </p>
                    {{ post.body| markdown | truncatewords:30 }}
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
        <div class="col-6">
            <p>{{ Profile.user.blog_comments.all | length }} <a href="{% url "posts:user_commented_post_list" Profile.user.id %}">comments</a></p>
            {% for comment in Profile.user.blog_comments.all %}
                <div class="border border-info p-1 m-1">
                    <div class="border p-1 m-3 col-11">
                        <h4>
                        <a href="{{ comment.post.get_absolute_url }}">
                            {{ comment.post.title }}
                        </a>
                        </h4>
                        Tags:
                        {% for tag in comment.post.tags.all %}
                            <a href="{% url "posts:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                            </a>
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                        </p>
                        <p class="date">
                        Published {{ comment.post.publish }} by {{ comment.author.email }}
                        </p>
                        {{ post.body| markdown | truncatewords:30 }}
                    </div>
                    <div class="card p-1 m-3 col-11">
                        <div class="card-body">
                        {{ comment.body | markdown }}
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">

                            <!-- <p class="small mb-0 ms-2"> Comment {{ forloop.counter }} by {{ comment.name }}</p> -->
                            <p class="small mb-0 ms-2">{{ comment.author.email }}</p>
                            </div>  
                            <div class="d-flex flex-row align-items-center">
                            <p class="small text-muted mb-0">  {{ comment.created }}</p>
                            </div>            
                        </div>
                        </div>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

Blog/users/templates/users/signup.html
{% extends "posts/base.html" %}

{% block title %}Log in{% endblock %}


{% block content %}

<div class="container m-2">
  <form method="post">
      {% csrf_token %}
      <div class="col-10">
          <div class="panel panel-default">
              <div class="panel-heading m-3 ">Singup</div>
              <div class="panel-body">
                {% for field in form %}
                <p>
                  {{ field.label_tag }}<br>
                  {{ field }}
                  {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                  {% endif %}
                  {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </p>
              {% endfor %}
                  <div class="col-md-6 col-md-offset-4 m-1">
                      <input name="signup" type="submit" value="signup" class="btn btn-success" /> &nbsp;
                      <a href="{% url 'users:login' %}">or Login</a>
                  </div>
              </div>
          </div>
      </div>
  </form>
</div>



{% endblock %}  

<!-- <h2>Sign up Form</h2>
<div>
  <ul class="menu">
    {% if request.user.is_authenticated %}
      <li><a href="{% url "users:logout" %}">log out- {{ request.user.email }}</a></li>
      
    {% else %}
      <li><a href="{% url "users:login" %}">log in</a></li>
      <li><a href="{% url "users:signup" %}">sign up</a></li>
    {% endif %}
  </ul>
</div>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>
 -->