Blog/posts/urls.py
from django.urls import path


from . import views
from .feeds import LatestPostsFeed


app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:user_id>', views.UserPostListView.as_view(), name='user_post_list'),
    path('commented/<int:user_id>', views.UserCommentedPostListView.as_view(), name='user_commented_post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    #path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('create', views.PostCreateView.as_view(), name='post_create'),
]

Blog/posts/templates/posts/post/commentedPostList.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}My Blog{% endblock %}

{% block sidebar %}  {% endblock %}  

{% block content %}

    {% for comment in comments %}
    <div class="border border-info p-1 m-1">
        <div class="border p-1 m-3 col-11">
            <h4>
            <a href="{{ comment.post.get_absolute_url }}">
                {{ comment.post.title }}
            </a>
            </h4>
            Tags:
            {% for tag in comment.post.tags.all %}
                <a href="{% url "posts:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
            </p>
            <p class="date">
            Published {{ comment.post.publish }} by {{ comment.author.email }}
            </p>
            {{ post.body| markdown | truncatewords:30 }}
        </div>
        <div class="card p-1 m-3 col-11">
            <div class="card-body">
            {{ comment.body | markdown }}
            <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">

                <!-- <p class="small mb-0 ms-2"> Comment {{ forloop.counter }} by {{ comment.name }}</p> -->
                <p class="small mb-0 ms-2">{{ comment.author.email }}</p>
                </div>  
                <div class="d-flex flex-row align-items-center">
                <p class="small text-muted mb-0">  {{ comment.created }}</p>
                </div>            
            </div>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}
    {% include "pagination.html" with page=page_obj %} 


{% endblock %}

Blog/posts/templates/posts/post/create.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label  class="form-label">Titel</label>
            <input type="text" name="title" class="form-control" placeholder="...">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Body</label>
            <textarea class="form-control" name="body" rows="14"></textarea>
        </div>
        <button type="submit" value="Add comment" class="btn btn-success">Add post</button>
    </form>
{% endblock %}

Blog/posts/templates/posts/post/detail.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div class="container">
  <div class="row py-3">
    <div class="col-1 col-lg-1"></div>
    <div class="col-9 col-lg-9">
      <h1>{{ post.title }}</h1>
      <p class="date">
        Published {{ post.publish }} by {{ post.author }}
      </p>
      {{ post.body|linebreaks }}
      <p>
        <a href="{% url "posts:post_share" post.id %}">
          Share this post
        </a>
      </p>
      <h2>Similar posts</h2>
      {% for post in similar_posts %}
        <p>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
      {% empty %}
        There are no similar posts yet.
      {% endfor %}
      <!-- {% with comments.count as total_comments %}
        <h2>
          {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
      {% endwith %} -->
      {% for comment in comments %}
      <div class="card mb-4">
        <div class="card-body">
          {{ comment.body | markdown }}
          <div class="d-flex justify-content-between">
            <div class="d-flex flex-row align-items-center">

              <!-- <p class="small mb-0 ms-2"> Comment {{ forloop.counter }} by {{ comment.name }}</p> -->
              <p class="small mb-0 ms-2"><a href="{% url "users:profile" comment.author.id %}">{{ comment.author.email }}</a></p>
            </div>  
            <div class="d-flex flex-row align-items-center">
              <p class="small text-muted mb-0">  {{ comment.created }}</p>
            </div>            
          </div>
        </div>
      </div>
      {% empty %}
        <p>There are no comments yet.</p>
      {% endfor %}
      {% include "pagination.html" with page=comments %}

      {% if new_comment %}
        <h4>Your comment has been added.</h4>
      {% endif %}
        <h3>Add a new comment</h3>
      <!-- comment form -->
      <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-3">
          <label for="comment">Comments:</label>
          <textarea class="form-control" rows="5" id="comment" name="body"></textarea>
        </div>
        <button type="submit" value="Add comment" class="btn btn-success">Add comment</button>
      </form> 
        
    </div>
    <div class="col-2 col-lg-2"></div>
  </div>
</div>
{% endblock %}

Blog/posts/templates/posts/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
      <li class="blockquote-footer p-1">
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% endfor %}
</ul>

Blog/posts/templates/posts/post/list.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}My Blog{% endblock %}

{% block sidebar %}  {% endblock %}  

{% block content %}

      {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
      {% endif %}
      {% for post in posts %}
      <div class="border p-1 m-3">
        <h4>
          <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
          </a>
        </h4>
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url "posts:post_list_by_tag" tag.slug %}">
              {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
        <p class="date">
          Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body| markdown | truncatewords:30 }}
      </div>
      {% endfor %}
      {% include "pagination.html" with page=page_obj %} 

{% endblock %}

Blog/posts/templates/posts/post/search.html
{% extends "posts/base.html" %}
{% load posts_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "posts:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

Blog/posts/templates/posts/post/share.html
{% extends "posts/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
          <label  class="form-label">To:</label>
          <input type="text" name="to" class="form-control" placeholder="example@email.com">
      </div>
      <div class="mb-3">
          <label for="exampleFormControlTextarea1" class="form-label">Comment</label>
          <textarea class="form-control" name="comment" rows="8"></textarea>
      </div>
      <button type="submit" value="Share post" class="btn btn-success">Share post</button>
    </form>
  {% endif %}
{% endblock %}