Blog/posts/urls.py
from django.urls import path


from . import views
from .feeds import LatestPostsFeed


app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:user_id>', views.UserPostListView.as_view(), name='user_post_list'),
    path('commented/<int:user_id>', views.UserCommentedPostListView.as_view(), name='user_commented_post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    #path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('create', views.PostCreateView.as_view(), name='post_create'),
]

Blog/posts/templates/posts/base.html
{% load posts_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>

  <meta charset="utf-8">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"> <!-- only for footer social icons-->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
    body {
      background: url('{% static "white-concrete-wall.jpg" %}') no-repeat fixed;
    }
    a {
      text-decoration: none;
    }
    ul {
      list-style-type: none;
    }
  </style>

</head>



<body class="d-flex flex-column min-vh-100">

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand"> Hi {{ request.user.profile.first_name }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse-fluid navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url "pages:home" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "users:user_list" %}">Users</a>
          </li>
          <li>
            <a class="nav-link" href="{% url "posts:post_list" %}">Posts</a>
          </li>
          <li>
            <a class="nav-link" href="{% url "posts:post_create" %}">PostCreate</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "users:logout" %}">log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "users:login" %}">log in</a>
            </li>
            <li>
              <a class="nav-link" href="{% url "users:signup" %}">sign up</a>
            </li>
          {% endif %}
        </ul>
        <form class="d-flex"  action="{% url "posts:post_search" %}" method="get">
          <input class="form-control me-2" type="search" name="query"placeholder="Search">
          <button class="btn btn-primary" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


  <div class="container">
    <div class="row py-3">
        <div class="col-3 col-lg-3 order-2">
          {% block sidebar %}  {% endblock %}  
        </div>
        <div class="col-9 col-lg-9" id="main">
          {% block content %}
          {% endblock %}  
        </div>
    </div>
  </div>

{% block content2 %}
{% endblock %} 


  <!-- Footer -->
  <footer class="bg-dark text-center text-white mt-auto" id="call" style="margin: 0% 0%; padding: 0% 0%;">
      <!-- Grid container -->
      <div class="container p-4">
        <!-- Section: Social media -->
        <section class="mb-4">
  
          <!-- Facebook -->
          <a class="btn btn-outline-light btn-floating m-1" id="#!" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>
    
          <!-- Twitter -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>
    
          <!-- Google -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>
    
          <!-- Instagram -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>
    
          <!-- Linkedin -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
    
          <!-- Github -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-white" href="https://github.com/amirkh75">Github.com</a>
      </div>
      <!-- Copyright -->
  </footer>
  <!-- End Footer -->
  
  
  </body>
  </html>